name: Build package

runs:
  using: "composite"
  steps:
    - name: Build package
      shell: bash
      run: yarn build

    - name: Archive build artifact
      uses: actions/upload-artifact@v3
      with:
        name: pkg-build-${{ github.run_id }}
        path: |
          build
          dist
